seed: 42

data_folder: ./data  
output_folder: ./results
save_folder: ./results/save
train_json: ./data/train_data.json
val_json: ./data/val_data.json
test_json: ./data/eval.json
phoneme_map: ./data/phoneme_to_id.json

number_of_epochs: 30
batch_size: 8
eval_batch_size: 8
lr: 0.0001
lr_wav2vec: 0.00005

hidden_dim: 512
num_phonemes: 43
num_error_types: 3

wav2vec2_hub: facebook/wav2vec2-large-xlsr-53
wav2vec2_freeze: False

sample_rate: 16000
max_audio_length: 320000

error_weight: 1.0
phoneme_weight: 1.0
task: both

grad_clipping: 5.0
weight_decay: 0.0001
dropout: 0.1

evaluate_every_epoch: True
show_samples: True
num_sample_show: 3

num_workers: 4
pin_memory: True
persistent_workers: True